<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database\Database.mdf;Integrated Security=True" SettingsObjectName="stage_isetna.Properties.Settings" SettingsPropertyName="chaine" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Etudiant" Member="Etudiants">
    <Type Name="Etudiant">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cin" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Prenom" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateNaissance" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Adresse" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CodePostal" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NiveauId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FiliereId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>